### ISSUE TITLE
Disable prn of captured values at execution time

### ISSUE THREAD

**Issue by RickMoynihan** [vvvvalvalval/scope-capture#25]
It would be useful for `spy` not to `prn` the results of captured values at execution time.

The problem I have is that some of the values I have in scope are massive, and `spy`'s printing of them can fill my repl with MBs of generated text.  Emacs then tries to syntax highlight this which causes it to slow down until I manage to get it to run `M-x cider-repl-clear-buffer`

It would be useful when dealing with larger data for spy to either disable the `prn` of values completely, or provide a new variant of `spy` that doesn't print at all, and leaves the captured values for you to evaluate later.

**Comment by vvvvalvalval** [comment]
@RickMoynihan That's one of the intended uses of custom loggers, are you aware of those? https://github.com/vvvvalvalval/scope-capture/blob/master/doc/Tutorial.md#customization

**Comment by RickMoynihan** [comment]
Thanks for the pointer, they look useful.

Is there an argument that a more sensible default would be to not print the runtime values (but still emit the rest of the information)?  And for people to opt in to the printing of those values?  I'm not sure  what its utility is as you can just drop in a println if that's what you want.

Otherwise I can see myself having to either package those customisations into a library and use that everywhere instead; or copy this code into all my project development environments.

Thanks again for wrapping up this workflow in a library though, it's super useful!

**Comment by vvvvalvalval** [comment]
You know, you can also call sc.apy/spy with no arguments, in which case the scope will still be saved without printing the value.
________________________________

**Comment by RickMoynihan** [comment]
Ahh perfect I hadn't realised that, that's exactly what I'm looking for!
