### ISSUE TITLE
Error in tutorial

### ISSUE THREAD

**Issue by eggsyntax** [vvvvalvalval/scope-capture#37]
Hi Val,

Just wanted to point out what looks like an error in the tutorial:
[EDIT - I originally wrote README by mistake, but I mean [this section of the tutorial](https://github.com/vvvvalvalval/scope-capture/blob/master/doc/Tutorial.md#disabling-code-sites). ]

> You can disable the side-effects of the spy and brk macros at a given Code Site by calling sc.api/disable!
> 
> ```
> (sc.api/dispose! -2)
> ```
> 

I assume you meant the example to use `disable!` rather than `dispose!`.

Thanks for scope-capture, terrific tool!

**Comment by vvvvalvalval** [comment]
Nice catch, thanks for reporting! It's fixed in master.
